services:
  - type: web
    name: skin-disease-detection
    runtime: python
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: |
      pip install --upgrade pip
      pip install -r ../requirements.txt
      startCommand: gunicorn -c frontend/gunicorn_config.py frontend.app:app
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 0 --workers 1 --threads 1 --worker-class sync --worker-tmp-dir /dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MODEL_PATH
        value: ../backend/models/model.h5
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
      - key: WEB_CONCURRENCY
        value: 1
